# Generated by Django 3.2.3 on 2024-07-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
